[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
address = "0x46c643c2054e71d3e869c76457d63887b58f3bb213f542afb5783dbb0dca91"
transaction_hash = "0x65de43cc6c3887d4dccd45590913e5aa0b7714c009e5548c512eef04c66e693"
block_number = 3
seed = "aeternum"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x5a279c79f409c5b667a0fd6f563f5bdb0f4aef94de36eb58991231a0f102ca4"
class_hash = "0x7c6eb6263d86c399efb3c6e5e2b18b64c1daba7104a4f146a5f164aec17b0be"
abi = "abis/deployments/KATANA/contracts/actions.json"
reads = []
writes = []
computed = []
name = "aeternum::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x3a7623f7accc19dabd50c2013b30ac8cccfbe865847e4e45ede842a672f6ab5"
name = "aeternum::models::card"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "card"
type = "CardType"
key = false

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "armor"
type = "u32"
key = false

[[models.members]]
name = "exp"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x54a4f4ddb931d12dd2f704ce29120f1d3e4d942f375961e3eafb5e1993b6b7f"
name = "aeternum::models::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "highest_score"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf00737ffe57c5c931bfec9a7ea66f76d5eaae12cacca6952dcee0c2e3d8038"
name = "dojo_starter::systems::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x23c28dcfad6be01ca6509fdb35fd2bed6622238397613c60da5d387a43c38d0"
name = "dojo_starter::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6e2ee7d4a068af18fe59d23d7b709e955df695695a1fdfe13b1d7b3f942c217"
name = "aeternum::models::player"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "health"
type = "u64"
key = false

[[models.members]]
name = "armor"
type = "u64"
key = false

[[models.members]]
name = "exp"
type = "u64"
key = false

[[models.members]]
name = "high_score"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e9c42b868b520d54bff1b7f4c9b91f39bb2e2ad1c39d6484fb5d8a95382e01"
name = "dojo_starter::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
