[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x46c643c2054e71d3e869c76457d63887b58f3bb213f542afb5783dbb0dca91"
transaction_hash = "0x65de43cc6c3887d4dccd45590913e5aa0b7714c009e5548c512eef04c66e693"
block_number = 3
seed = "aeternum"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x5a279c79f409c5b667a0fd6f563f5bdb0f4aef94de36eb58991231a0f102ca4"
class_hash = "0x2feb064fe957f21b69635f723ce8dc38b2d3181d196135b4979a7454ad3664e"
original_class_hash = "0x2feb064fe957f21b69635f723ce8dc38b2d3181d196135b4979a7454ad3664e"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/aeternum_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "aeternum::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x3a7623f7accc19dabd50c2013b30ac8cccfbe865847e4e45ede842a672f6ab5"
original_class_hash = "0x3a7623f7accc19dabd50c2013b30ac8cccfbe865847e4e45ede842a672f6ab5"
abi = "abis/deployments/models/aeternum_models_card.json"
name = "aeternum::models::card"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "card"
type = "CardType"
key = false

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "armor"
type = "u32"
key = false

[[models.members]]
name = "exp"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x54a4f4ddb931d12dd2f704ce29120f1d3e4d942f375961e3eafb5e1993b6b7f"
original_class_hash = "0x54a4f4ddb931d12dd2f704ce29120f1d3e4d942f375961e3eafb5e1993b6b7f"
abi = "abis/deployments/models/aeternum_models_game.json"
name = "aeternum::models::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "highest_score"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6e2ee7d4a068af18fe59d23d7b709e955df695695a1fdfe13b1d7b3f942c217"
original_class_hash = "0x6e2ee7d4a068af18fe59d23d7b709e955df695695a1fdfe13b1d7b3f942c217"
abi = "abis/deployments/models/aeternum_models_player.json"
name = "aeternum::models::player"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "health"
type = "u64"
key = false

[[models.members]]
name = "armor"
type = "u64"
key = false

[[models.members]]
name = "exp"
type = "u64"
key = false

[[models.members]]
name = "high_score"
type = "u64"
key = false
