kind = "DojoModel"
class_hash = "0x2db8eb9f6c8d178885eea8f2c4b0b264a646f18d4962264c4ff5928aaf3becc"
original_class_hash = "0x2db8eb9f6c8d178885eea8f2c4b0b264a646f18d4962264c4ff5928aaf3becc"
abi = "manifests/dev/abis/base/models/aeternum_models_player.json"
name = "aeternum::models::player"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "x"
type = "u32"
key = false

[[members]]
name = "y"
type = "u32"
key = false

[[members]]
name = "hp"
type = "u32"
key = false

[[members]]
name = "max_hp"
type = "u32"
key = false

[[members]]
name = "shield"
type = "u32"
key = false

[[members]]
name = "max_shield"
type = "u32"
key = false

[[members]]
name = "exp"
type = "u32"
key = false

[[members]]
name = "high_score"
type = "u32"
key = false

[[members]]
name = "total_moves"
type = "u32"
key = false
