kind = "DojoModel"
class_hash = "0xd7622b5c43d9f99fdfd4039ce334ae07a0c66c54157356336d3f64f7a9676e"
original_class_hash = "0xd7622b5c43d9f99fdfd4039ce334ae07a0c66c54157356336d3f64f7a9676e"
abi = "manifests/dev/abis/base/models/aeternum_models_card.json"
name = "aeternum::models::card"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "card_type"
type = "CardType"
key = false

[[members]]
name = "hp"
type = "u32"
key = false

[[members]]
name = "max_hp"
type = "u32"
key = false

[[members]]
name = "shield"
type = "u32"
key = false

[[members]]
name = "max_shield"
type = "u32"
key = false
