kind = "DojoModel"
class_hash = "0x54a4f4ddb931d12dd2f704ce29120f1d3e4d942f375961e3eafb5e1993b6b7f"
original_class_hash = "0x54a4f4ddb931d12dd2f704ce29120f1d3e4d942f375961e3eafb5e1993b6b7f"
abi = "manifests/dev/abis/base/models/aeternum_models_game.json"
name = "aeternum::models::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "highest_score"
type = "u64"
key = false
