// Generated by dojo-bindgen on Sun, 7 Apr 2024 09:33:21 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `aeternum::models::CardType` enum
public enum CardType {
    Player,
    Monster,
    Item,
    Hidden,
    None,
}


// Model definition for `aeternum::models::Card` model
public class Card : ModelInstance {
    [ModelField("game_id")]
    public uint game_id;

    [ModelField("x")]
    public byte x;

    [ModelField("y")]
    public byte y;

    [ModelField("card")]
    public CardType card;

    [ModelField("health")]
    public uint health;

    [ModelField("armor")]
    public uint armor;

    [ModelField("exp")]
    public uint exp;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        