// Generated by dojo-bindgen on Sun, 7 Apr 2024 09:33:21 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `aeternum::models::Game` model
public class Game : ModelInstance {
    [ModelField("game_id")]
    public uint game_id;

    [ModelField("player")]
    public FieldElement player;

    [ModelField("highest_score")]
    public ulong highest_score;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        