// Generated by dojo-bindgen on Tue, 2 Apr 2024 22:10:13 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `aeternum::models::Player` model
public class Player : ModelInstance {
    [ModelField("game_id")]
    public uint game_id;

    [ModelField("player")]
    public FieldElement player;

    [ModelField("health")]
    public ulong health;

    [ModelField("armor")]
    public ulong armor;

    [ModelField("exp")]
    public ulong exp;

    [ModelField("high_score")]
    public ulong high_score;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        