kind = "DojoContract"
class_hash = "0x7c6eb6263d86c399efb3c6e5e2b18b64c1daba7104a4f146a5f164aec17b0be"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "aeternum::systems::actions::actions"
